# Notas Tercer Seccion - Numpy
Elaboradas por Diego Chavez

## Numpy Array vs. Listas

## 1. Indexacion
Este concepto se refiere a acceder a un elemento de un array dando la posicion mediante un ENTERO, asi:

In [ ]:
import numpy

a = numpy.arange(1,11,1) #crea un arreglo con numeros del 1 al 10 de 1-1
print(a)

print('-----')
print(a[0], a[-1])
print('-----')
print(a[0:-4]) # equivalente a a[0:6]
print('-----')
print(a[0:9:2]) # De dos en dos, creando pasos de avance
print('-----')
print(a[[0,7]]) # Sobre Indexacion genera un array 
type(a[[0,7]])




[ 1  2  3  4  5  6  7  8  9 10]
-----
1 10
-----
[1 2 3 4 5 6]
-----
[1 3 5 7 9]
-----
[1 8]


numpy.ndarray

## 2. Modificaciones

In [ ]:
import numpy as np
a = np.arange(5)
print(a)

print("-----")
a = np.insert(a, (0,-1),8) # Inserta en el objeto a y en las posiciones 0 y -1, el numero 8
print(a)

print("-----")
a = np.append(a, [-3,2]) # Inserta en el objeto a en la ultima posicion, los valores -3 y 2
print(a)

print("-----")
a = np.delete(a, [0]) # Borra en el objeto a el valor que esta en la posicion 0
print(a)



[0 1 2 3 4]
-----
[8 0 1 2 3 8 4]
-----
[ 8  0  1  2  3  8  4 -3  2]
-----
[ 0  1  2  3  8  4 -3  2]


## 3. Flatten y Ravel

In [24]:
import numpy as np

a = np.arange(6)
print(a)

print("-----")
a = a.reshape(3,2)
print(a)

print("-----")
a = a.reshape(3,1,2)
print(a)

print("-----")
a = a.reshape(6,1)
print(a)


print("-----")
a = a.flatten()
print(a)

[0 1 2 3 4 5]
-----
[[0 1]
 [2 3]
 [4 5]]
-----
[[[0 1]]

 [[2 3]]

 [[4 5]]]
-----
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
-----
[0 1 2 3 4 5]


## 4. Concatenate

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.arange(1,5).reshape(2,2)
print(a) 
print(b)

print("-----")
print(a.shape)
print(b.shape)

print("-----")
c = np.array([[5,6]]) # Matriz con 1 fila y 2 columnas
print(c)

print("-----")
print(c.shape)


# CONCATENADO POR FILAS
print("-----")
x=np.concatenate((a,c), axis=0) # Concatena las matrices a y c, donde c queda como fila en a, obteniendo una matriz de 3x2: 0 = Filas
print(x)

print("-----")
print(x.shape)

# CONCATENADO POR COLUMNAS
print("-----")
y=np.concatenate((a,c.T), axis=1) # Cantidad de Filas de A, debe ser igual a cantidad de filas de C, por eso hago la traspuesta 
print(y)

print("-----")
print(y.shape)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
-----
(2, 2)
(2, 2)
-----
[[5 6]]
-----
(1, 2)
-----
[[1 2]
 [3 4]
 [5 6]]
-----
(3, 2)
-----
[[1 2 5]
 [3 4 6]]
-----
(2, 3)
